a = input('What is your name: ')
b= int(input('What is your age: '))
c= input('where do you live: ')
d = input('what is your profession: ')
print('Hello {0} you are {1} you live in {2}  and you work as a {3}'.format(a,b,c,d)) 
